# Server Configuration
server:
  port: 8081

# Spring Datasource Configuration (MySQL)
spring:
  application:
    name: PRODUCTMICROSERVICE
  data:
     mongodb:
       uri: mongodb://BHANU:BHANU123@localhost:27017/myntraproducts?authSource=admin&retryWrites=true&w=majority


  


  

# Redis Cache Configuration

  cache:
    type: redis
  



# Pagination and Sorting defaults (optional)
product:
  pagination:
    default-page-size: 10
  sorting:
    default-sort-by: price

# Logging Configuration
logging:
  level:
    org.springframework: INFO
    com.yourpackage: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true



