# Server Configuration
server:
  port: 8081



  


  

# Redis Cache Configuration

  cache:
    type: redis
  



# Pagination and Sorting defaults (optional)
product:
  pagination:
    default-page-size: 10
  sorting:
    default-sort-by: price

# Logging Configuration
logging:
  level:
    org.springframework: INFO
    com.yourpackage: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true



