# Server Configuration
server:
  port: 8081

# Spring Datasource Configuration (MySQL)
spring:
  application:
    name: PRODUCTMICROSERVICE
  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@127.0.0.1:27017/myntraproducts?authSource=myntraproducts&authMode=scram-sha1&directConnection=true&serverSelectionTimeoutMS=2000
    redis:
      host: localhost
      port: 6379


  

# Redis Cache Configuration

  cache:
    type: redis
  



# Pagination and Sorting defaults (optional)
product:
  pagination:
    default-page-size: 10
  sorting:
    default-sort-by: price

# Logging Configuration
logging:
  level:
    org.springframework: INFO
    com.yourpackage: DEBUG
    org.springframework.data.mongodb: DEBUG



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true
